#!/usr/bin/env python3
"""
GitLab Security Guardian - LLM Orchestrator

This script orchestrates the autonomous security auditing of GitLab Merge Requests.
It fetches MR code changes, runs security analysis using Google Gemini LLM,
and comments findings back on the Merge Request.
"""

import argparse
import logging
import os
import urllib.parse
from typing import Dict, Any, List
import requests
from google import genai
from google.genai import types

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger("security-guardian")


def fetch_merge_request_diff(project_id: str, mr_iid: int, gitlab_url: str, token: str) -> List[Dict[str, Any]]:
    """
    Fetches the changes/diff of a target Merge Request using the GitLab API.
    
    API Endpoint: GET /projects/:id/merge_requests/:merge_request_iid/changes
    """
    logger.info(f"Fetching diff for MR !{mr_iid} in project {project_id}...")
    
    safe_project_id = urllib.parse.quote_plus(project_id)
    url = f"{gitlab_url.rstrip('/')}/api/v4/projects/{safe_project_id}/merge_requests/{mr_iid}/changes"
    
    headers = {
        "PRIVATE-TOKEN": token,
        "Accept": "application/json"
    }
    
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    
    data = response.json()
    changes = data.get("changes", [])
    logger.info(f"Successfully fetched diff. Total modified files: {len(changes)}")
    return changes


def analyze_diff_with_gemini(changes: List[Dict[str, Any]], gemini_key: str) -> str:
    """
    Analyzes Merge Request changes for potential security vulnerabilities using Gemini.
    
    Args:
        changes: List of change/diff objects from GitLab API.
        gemini_key: API key for Google Gemini.
        
    Returns:
        Markdown table string generated by the LLM.
    """
    logger.info("Preparing diff content for Gemini analysis...")
    
    diff_content_parts = []
    for change in changes:
        new_path = change.get("new_path")
        diff = change.get("diff", "")
        if diff:
            diff_content_parts.append(f"File: {new_path}\nDiff:\n{diff}\n" + "="*80)
            
    diff_content = "\n".join(diff_content_parts)
    
    if not diff_content.strip():
        logger.info("No code changes detected in the diff.")
        return "✅ **No code changes detected in this Merge Request.**"
        
    logger.info("Initializing Gemini Client and sending request...")
    
    client = genai.Client(api_key=gemini_key)
    
    system_instruction = (
        "You are a strict Senior Application Security Engineer. "
        "Analyze the provided git diff for security vulnerabilities, logical flaws, "
        "injection risks, and bad practices. "
        "Output ONLY a beautifully formatted markdown table with your findings. "
        "The table must have these columns: File, Line, Vulnerability Type, Severity, and Description/Recommendation. "
        "Do not include any introductory or concluding text, warnings, or explanations outside the table itself."
    )
    
    prompt = (
        f"Please perform a security review on the following git diff:\n\n{diff_content}"
    )
    
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
            )
        )
        logger.info("Gemini analysis complete.")
        return response.text
    except Exception as e:
        logger.error(f"Failed to generate content from Gemini API: {str(e)}")
        raise


def post_mr_comment(project_id: str, mr_iid: int, comment: str, gitlab_url: str, token: str) -> Dict[str, Any]:
    """
    Posts a summary comment back to the Merge Request with findings.
    
    API Endpoint: POST /projects/:id/merge_requests/:merge_request_iid/notes
    """
    logger.info(f"Posting security summary comment to MR !{mr_iid}...")
    
    safe_project_id = urllib.parse.quote_plus(project_id)
    url = f"{gitlab_url.rstrip('/')}/api/v4/projects/{safe_project_id}/merge_requests/{mr_iid}/notes"
    
    headers = {
        "PRIVATE-TOKEN": token,
        "Content-Type": "application/json"
    }
    
    payload = {"body": comment}
    
    response = requests.post(url, headers=headers, json=payload)
    response.raise_for_status()
    
    logger.info("Successfully posted comment to Merge Request.")
    return response.json()


def main():
    parser = argparse.ArgumentParser(description="GitLab Security Guardian LLM Orchestrator")
    parser.add_argument("--project-id", required=True, help="GitLab Project ID or Path (e.g. soft-hive-group/project)")
    parser.add_argument("--mr-iid", required=True, type=int, help="Merge Request Internal ID (IID)")
    parser.add_argument("--gitlab-url", default=os.getenv("GITLAB_API_URL", "https://gitlab.com"), help="GitLab base URL")
    parser.add_argument("--token", default=os.getenv("GITLAB_TOKEN"), help="GitLab Private Access Token")
    parser.add_argument("--gemini-key", default=os.getenv("GEMINI_API_KEY"), help="Google Gemini API Key")
    
    args = parser.parse_args()
    
    token = args.token or os.getenv("GITLAB_PERSONAL_ACCESS_TOKEN")
    if not token:
        logger.error("GitLab access token not provided. Use --token or set GITLAB_TOKEN/GITLAB_PERSONAL_ACCESS_TOKEN env variables.")
        exit(1)
        
    gemini_key = args.gemini_key
    if not gemini_key:
        logger.error("Gemini API Key not provided. Use --gemini-key or set GEMINI_API_KEY env variable.")
        exit(1)
        
    try:
        # 1. Fetch changes
        changes = fetch_merge_request_diff(args.project_id, args.mr_iid, args.gitlab_url, token)
        
        # 2. Analyze using Gemini
        report_markdown = analyze_diff_with_gemini(changes, gemini_key)
        
        # 3. Post comment back to GitLab MR
        full_comment = f"## 🛡️ GitLab Security Guardian LLM Report\n\n{report_markdown}"
        post_mr_comment(args.project_id, args.mr_iid, full_comment, args.gitlab_url, token)
        
        logger.info("Orchestration pipeline finished successfully.")
        
    except Exception as e:
        logger.critical(f"Guardian orchestrator failed: {str(e)}")
        exit(1)


if __name__ == "__main__":
    main()
